global:
  scrape_interval:     3s

  external_labels:
    monitor: 'fast_api-app'


scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'

    dns_sd_configs:
      - names: [ 'app' ]
        port: 8000
        type: A
        refresh_interval: 5s