{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests pet second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total{handler=\"/api/users/me\", method=\"GET\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/users/{id}\", method=\"GET\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/tweets\", method=\"GET\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/tweets\", method=\"POST\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/medias\", method=\"POST\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/users/{id}/follow\", method=\"POST\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/tweets/{id}/likes\", method=\"POST\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/tweets/{id}\", method=\"DELETE\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/users/{id}/follow\", method=\"DELETE\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "increase(http_requests_total{handler=\"/api/tweets/{id}/likes\", method=\"DELETE\", status=\"2xx\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status!=\"2xx\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[30s])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Requests pet second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/users/me\", method=\"GET\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/users/me\", method=\"GET\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/users/{id}\", method=\"GET\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/users/{id}\", method=\"GET\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/tweets\", method=\"GET\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/tweets\", method=\"GET\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/tweets\", method=\"POST\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/tweets\", method=\"POST\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/medias\", method=\"POST\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/medias\", method=\"POST\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/users/{id}/follow\", method=\"POST\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/users/{id}/follow\", method=\"POST\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/tweets/{id}/likes\", method=\"POST\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/tweets/{id}/likes\", method=\"POST\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/tweets/{id}\", method=\"DELETE\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/tweets/{id}\", method=\"DELETE\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/users/{id}/follow\", method=\"DELETE\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/users/{id}/follow\", method=\"DELETE\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/api/tweets/{id}/likes\", method=\"DELETE\"}[30s])\n/\nrate(http_request_duration_seconds_count{handler=\"/api/tweets/{id}/likes\", method=\"DELETE\"}[30s])",
     "legendFormat": "{{method}} {{ handler }}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\", status=\"2xx\"}[1m]))",
     "legendFormat": "HTTP 200"
    },
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\", status=\"4xx\"}[1m]))",
     "legendFormat": "HTTP 400"
    },
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\", status=\"5xx\"}[1m]))",
     "legendFormat": "HTTP 500"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}